%ifndef COLORS_INC
%define COLORS_INC

%define VGA_BLACK 0
%define VGA_BLUE 1
%define VGA_GREEN 2
%define VGA_CYAN 3
%define VGA_RED 4
%define VGA_MAGENTA 5
%define VGA_BROWN 6
%define VGA_GREY 7
%define VGA_DARK_GREY 8
%define VGA_BRIGHT_BLUE 9
%define VGA_BRIGHT_GREEN 10
%define VGA_BRIGHT_CYAN 11
%define VGA_BRIGHT_RED 12
%define VGA_BRIGHT_MAGENTA 13
%define VGA_YELLOW 14
%define VGA_WHITE 15

%endif ;COLORS_INC